### ISSUE TITLE
Your website does not work on Firefox

### ISSUE THREAD

**Issue by Tylersuard** [twilio/twilio-python#757] opened 2024-02-08 07:04 UTC
When I try to verify my toll-free number, I am unable to click on the search button or the submit button.

**Comment by tiwarishubham635** [comment] 2024-04-04 17:33
If you referring to the [console](https://www.twilio.com/login), please report the issue at [help.twilio.com](https://help.twilio.com/)

**Comment by tiwarishubham635** [comment] 2024-04-05 10:41
Closing as the issue is not related to SDK

**Closed** 2024-04-05 10:41 UTC
Labels: status: waiting for feedback
