### ISSUE TITLE
Camel case TwiML attributes are ignored and thus breaking functionality (all converted to lowercase in XML and causing Schema validation warnings)

### ISSUE THREAD

**Issue by yfurbach** [twilio/twilio-python#349] opened 2017-06-08 07:56 UTC
**Version:**
6.3.0
**API Subdomain (api/taskrouter/ip_messaging):**
twilio.twiml.TwiML

### Code Snippet
```python
from twilio.twiml.voice_response import Gather
gather = Gather(numDigits=1, finishOnKey="", timeout=10, action="confirm", method="POST")
gather.to_xml()
```

### _Expected_ Result
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Gather action="confirm" finishOnKey="" method="POST" numDigits="1" timeout="10" />
```

### _Actual_ Result
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Gather action="confirm" finishonkey="" method="POST" numdigits="1" timeout="10" />
```

### Steps to Reproduce
1. Use ```Gather``` from code snippet in TwiML response
2. ```confirm``` method should expect either * to confirm or # to reenter digits requested by a previous ```Gather```
3. because lower case ```finishonkey```is ignored, # aborts the ```Gather``` and thus ends the call, instead of submitting to ```confirm```and prompting for new digits. In addition, numdigits is also ignored

A warning can be seen in the Voice Logs Calls:
NOTIFICATION SID: NO050b1049d0afa5ec52e4fa499ef2891f
WARNING: 12200 Schema validation warning
DESCRIPTION: Attribute 'finishonkey' is not allowed to appear in element 'Gather'.

If I do this hack in twilio.twiml.__init__.py, it works again
```python
def lower_camel(string):
    # do not convert to lower case
    return string
    result = "".join([x.title() for x in string.split('_')])
    if not result:
        return result

    return result[0].lower() + result[1:]
```

**Comment by ilanbiala** [comment] 2017-06-08 18:08
@yfurbach attributes in Python are specified using snake case, i.e. `finish_on_key` or `status_callback`. Did a previous version support camel case attributes?

**Comment by yfurbach** [comment] 2017-06-09 08:43
@ilanbiala Thank you and yes, obviously it worked before. We encountered this while upgrading from 5.6.0
It is a bit unclear from the documentation, as it is mostly ```**kwargs``` that are not specified any further.
In 6.3.0 in ```VoiceResponse.gather(...)``` I now notice the snake case, but I could no longer use this method because of wrong nesting as described in issue [#341](https://github.com/twilio/twilio-python/issues/341), so I had to switch to ```Gather()```.

I just checked the 5.6.0 code and there it was specified as camel case
```python
class Gather(Verb):
    """Gather digits from the caller's keypad
    :param action: URL to which the digits entered will be sent
    :param method: submit to 'action' url using GET or POST
    :param numDigits: how many digits to gather before returning
    :param timeout: wait for this many seconds before returning
    :param finishOnKey: key that triggers the end of caller input
    """
    GET = 'GET'
    POST = 'POST'
    nestables = ['Say', 'Play', 'Pause']

    def __init__(self, **kwargs):
        super(Gather, self).__init__(**kwargs)
```

Anyway, I will change our code to snake case.

**Comment by ilanbiala** [comment] 2017-06-09 17:00
Okay, closing. Take a look at the code snippet I posted in #341 as well.

**Closed by ilanbiala** 2017-06-09 17:00 UTC

**Comment by actioncrypto** [comment] 2017-06-12 15:31
I just posted this same behavior in another thread (didn't see this one) and can confirm it worked before in v5, but broke in v6 because of the `lower_camel` method. Can be worked around by changing all python code that has camel case params and converting them to snake case so the method works as intended. This should be noted in the migration docs...

**Comment by efossier** [comment] 2017-12-16 01:58
@actioncrypto This should be fixed for good in the next release. Sorry for the inconvenience, we had a bit of a mixup where we fixed it in a PR here but it was getting generated incorrectly by our code generator and thus overwriting it.

**Comment by lborda** [comment] 2018-02-14 17:24
has that been fixed already ?
