### ISSUE TITLE
ResourceWarning: unclosed ssl socket

### ISSUE THREAD

**Issue by jpodpro** [twilio/twilio-python#585] opened 2021-12-28 22:51 UTC
### Issue Summary

When using `client.calls.create` to send a voice message i get an unclosed ssl socket ResourceWarning. The call and translation works fine.

UPDATE: this doesn't happen immediatey on the first run - i have to wait 20 seconds or so. however subsequent calls to the code without restarting the server result in the given ResourceWarning error instantly.

### Code Snippet
```python
message = 'shubbit yo face'
client = Client() if is_production else Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
client_call = client.calls.create(
    status_callback=twilio_status_callback_url_builder(),
    status_callback_event=['initiated', 'ringing', 'answered', 'completed'],
    status_callback_method='POST',
    to="+1{0}".format(phone_number),
    from_=settings.TWILIO_PHONE_NUMBER,
    url=twilio_voice_callback_url_builder({
        'say': json.dumps(message)
    })
)
```

### Exception/Log
```
C:\<hidden>\Python\Python39\lib\pathlib.py:189: ResourceWarning: unclosed <ssl.SSLSocket fd=1636, f
amily=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<hidden>', 52915), raddr=('<hidden>', 443)>
  return [p.lower() for p in parts]
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=1756, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, la
ddr=('<hidden>', 52913), raddr=('<hidden>', 443)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

### Technical details:
* twilio-python version: 7.4.0
* python version: 3.9.6

**Comment by jpodpro** [comment] 2021-12-31 00:52
after much research it seems like this is a consequence of pooling / reusing connections. i found someone else with the same issue using a google api client. if this is the case perhaps some documentation about it would be helpful as i have spent quite a bit of time researching and digging through the api code to find a proper way to deal with this. for now i am simply using `warnings.simplefilter("ignore", ResourceWarning)` to ignore it.

**Comment by eshanholtz** [comment] 2022-01-07 20:01
Hi @jpodpro 

We actually have the ability to override the pooling connections behavior built-in! To do this, you will need to pass in a [Custom HTTP Client](https://www.twilio.com/docs/libraries/python/custom-http-clients-python#) that has the `pool_connections` flag turned off. For example:

```python
import os
from twilio.rest import Client
from twilio.http.http_client import TwilioHttpClient

# Override default pooling behavior
custom_http_client = TwilioHttpClient(pool_connections=False)

client = Client(os.getenv("ACCOUNT_SID"), os.getenv("AUTH_TOKEN"),
                http_client=custom_http_client)

message = client.messages \
    .create(
        to="+15558675310",
        body="Hey there!",
        from_="+15017122661"
    )

print('Message SID: {}'.format(message.sid))
```

**Comment by eshanholtz** [comment] 2022-02-08 02:38
Closing due to lack of customer response. Hope it worked!

**Closed by eshanholtz** 2022-02-08 02:38 UTC
Labels: type: question, status: waiting for feedback

**Comment by tamird** [comment] 2024-02-21 09:10
I am still seeing this. It is caused by the fact that the passed-in http client is never closed, and there's no way to close it from the outside.

The client is retained [here](https://github.com/twilio/twilio-python/blob/d8fa9e8e6859c0a163fbfa7e2796b1ef69676264/twilio/base/client_base.py#L59), but is not exposed, so it can never be closed.

Disabling connection pooling is not the right solution.
