### ISSUE TITLE
pyjwt==1.7.1 dependency needs to be updated.

### ISSUE THREAD

**Issue by amsal-muhammad** [twilio/twilio-python#565] opened 2021-05-31 13:39 UTC
pyjwt<3,>=2 (from djangorestframework-simplejwt==4.7.1->-r /var/folders/q8/mbmfgbvn0mjfb0kd6s31cznr0000gn/T/pipenvl7v0akw4requirements/pipenv-9zfxzs7n-constraints.txt (line 15))
  pyjwt==1.7.1 (from twilio==6.59.0->-r /var/folders/q8/mbmfgbvn0mjfb0kd6s31cznr0000gn/T/pipenvl7v0akw4requirements/pipenv-9zfxzs7n-constraints.txt (line 24))

**Comment by rmaciejczyk** [comment] 2021-05-31 14:03
@amsal-muhammad I believe this issue is a duplicate of #556

**Comment by JenniferMah** [comment] 2021-06-02 20:20
Hi @amsal-muhammad! @rmaciejczyk is correct. This is a repeat of #556. I'm going to close this issue as a duplicate. Please add a +1 to #556 and follow the progress on upgrading to PyJWT 2.0 in issue #556.

**Closed by JenniferMah** 2021-06-02 20:20 UTC
Labels: status: duplicate
